version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Built Successfully"
      
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output      
            
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A second hello"
      - run: mkdir -p my_work
      - run: echo "Trying out work" > my_work/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_work
          # Must be relative path from root
          paths:
            - echo-output 
  hold:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Holded"
      
  three:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!";
          fi
   
  four:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A most familiar hello"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_work

      - run: |
          if [[ $(cat my_work/echo-output) == "Trying out work" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; 
          fi
  
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deployed Successfully"  
      
workflows:
  version: 2
  build_one_two_hold_three_four_deploy:
    jobs:
      - build
      - one:
          requires:
            - build
      - two:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build 
      - three:
          requires:
            - build
      - four:
          requires:
            - build
      - deploy:
          requires:
            - one
            - two
            - hold
            - three
            - four
